a=int(input("Enter the number:"))
b=int(input("Enter the number:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("square root:",a**0.5)
print("power:",a**b)
print("modulus:",a%b)
print("floor division:",a//b)
